from pathlib import Path

import pytest

from metakb.harvesters.cbioportal import (
    CBioPortalHarvestedData,
    CBioPortalHarvester,
    CBioPortalStudyName,
)


@pytest.fixture(scope="session")
def stjude_all_2015_fixture():
    return CBioPortalHarvestedData(
        study_name=CBioPortalStudyName.ALL_STJUDE_2015,
        variants=[
            {
                "Hugo_Symbol": "PAX5",
                "Entrez_Gene_Id": "",
                "Center": "St. Jude Children's Research Hospital",
                "NCBI_Build": "GRCh37",
                "Chromosome": "9",
                "Start_Position": "37015005",
                "End_Position": "37015005",
                "Strand": "+",
                "Consequence": "missense_variant",
                "Variant_Classification": "Missense_Mutation",
                "Variant_Type": "SNP",
                "Reference_Allele": "A",
                "Tumor_Seq_Allele1": "A",
                "Tumor_Seq_Allele2": "C",
                "dbSNP_RS": "",
                "dbSNP_Val_Status": "",
                "Tumor_Sample_Barcode": "SJINF023",
                "Matched_Norm_Sample_Barcode": "",
                "Match_Norm_Seq_Allele1": "",
                "Match_Norm_Seq_Allele2": "",
                "Tumor_Validation_Allele1": "",
                "Tumor_Validation_Allele2": "",
                "Match_Norm_Validation_Allele1": "",
                "Match_Norm_Validation_Allele2": "",
                "Verification_Status": "",
                "Validation_Status": "",
                "Mutation_Status": "Somatic",
                "Sequencing_Phase": "",
                "Sequence_Source": "",
                "Validation_Method": "",
                "Score": "",
                "BAM_File": "",
                "Sequencer": "Illumina HiSeq 2500",
                "t_ref_count": "97",
                "t_alt_count": "17",
                "n_ref_count": "29",
                "n_alt_count": "0",
                "HGVSc": "ENST00000358127.4:c.399T>G",
                "HGVSp": "p.Ser133Arg",
                "HGVSp_Short": "p.S133R",
                "Transcript_ID": "ENST00000358127",
                "RefSeq": "NM_001280556.1",
                "Protein_position": "133",
                "Codons": "agT/agG",
                "Hotspot": "0",
                "Amino_Acid_Change": "S133R",
            },
            {
                "Hugo_Symbol": "NRAS",
                "Entrez_Gene_Id": "",
                "Center": "St. Jude Children's Research Hospital",
                "NCBI_Build": "GRCh37",
                "Chromosome": "1",
                "Start_Position": "115258744",
                "End_Position": "115258744",
                "Strand": "+",
                "Consequence": "missense_variant",
                "Variant_Classification": "Missense_Mutation",
                "Variant_Type": "SNP",
                "Reference_Allele": "C",
                "Tumor_Seq_Allele1": "C",
                "Tumor_Seq_Allele2": "T",
                "dbSNP_RS": "",
                "dbSNP_Val_Status": "",
                "Tumor_Sample_Barcode": "SJINF024",
                "Matched_Norm_Sample_Barcode": "",
                "Match_Norm_Seq_Allele1": "",
                "Match_Norm_Seq_Allele2": "",
                "Tumor_Validation_Allele1": "",
                "Tumor_Validation_Allele2": "",
                "Match_Norm_Validation_Allele1": "",
                "Match_Norm_Validation_Allele2": "",
                "Verification_Status": "",
                "Validation_Status": "",
                "Mutation_Status": "Somatic",
                "Sequencing_Phase": "",
                "Sequence_Source": "",
                "Validation_Method": "",
                "Score": "",
                "BAM_File": "",
                "Sequencer": "Illumina HiSeq 2500",
                "t_ref_count": "470",
                "t_alt_count": "48",
                "n_ref_count": "20",
                "n_alt_count": "0",
                "HGVSc": "ENST00000369535.4:c.38G>A",
                "HGVSp": "p.Gly13Asp",
                "HGVSp_Short": "p.G13D",
                "Transcript_ID": "ENST00000369535",
                "RefSeq": "NM_002524.4",
                "Protein_position": "13",
                "Codons": "gGt/gAt",
                "Hotspot": "0",
                "Amino_Acid_Change": "G13D",
            },
            {
                "Hugo_Symbol": "PIK3CA",
                "Entrez_Gene_Id": "",
                "Center": "St. Jude Children's Research Hospital",
                "NCBI_Build": "GRCh37",
                "Chromosome": "3",
                "Start_Position": "178952085",
                "End_Position": "178952085",
                "Strand": "+",
                "Consequence": "missense_variant",
                "Variant_Classification": "Missense_Mutation",
                "Variant_Type": "SNP",
                "Reference_Allele": "A",
                "Tumor_Seq_Allele1": "A",
                "Tumor_Seq_Allele2": "G",
                "dbSNP_RS": "",
                "dbSNP_Val_Status": "",
                "Tumor_Sample_Barcode": "SJINF024",
                "Matched_Norm_Sample_Barcode": "",
                "Match_Norm_Seq_Allele1": "",
                "Match_Norm_Seq_Allele2": "",
                "Tumor_Validation_Allele1": "",
                "Tumor_Validation_Allele2": "",
                "Match_Norm_Validation_Allele1": "",
                "Match_Norm_Validation_Allele2": "",
                "Verification_Status": "",
                "Validation_Status": "",
                "Mutation_Status": "Somatic",
                "Sequencing_Phase": "",
                "Sequence_Source": "",
                "Validation_Method": "",
                "Score": "",
                "BAM_File": "",
                "Sequencer": "Illumina HiSeq 2500",
                "t_ref_count": "1010",
                "t_alt_count": "217",
                "n_ref_count": "30",
                "n_alt_count": "0",
                "HGVSc": "ENST00000263967.3:c.3140A>G",
                "HGVSp": "p.His1047Arg",
                "HGVSp_Short": "p.H1047R",
                "Transcript_ID": "ENST00000263967",
                "RefSeq": "NM_006218.2",
                "Protein_position": "1047",
                "Codons": "cAt/cGt",
                "Hotspot": "0",
                "Amino_Acid_Change": "H1047R",
            },
        ],
        patients=[
            {
                "PATIENT_ID": "SJINF001",
                "COHORT": "INF_MLLr_Discovery",
                "AGE": "0.17",
                "SEX": "Female",
            },
            {
                "PATIENT_ID": "SJINF002",
                "COHORT": "INF_MLLr_Discovery",
                "AGE": "0.58",
                "SEX": "Male",
            },
            {
                "PATIENT_ID": "SJINF003",
                "COHORT": "INF_MLLr_Discovery",
                "AGE": "0.58",
                "SEX": "Male",
            },
        ],
        samples=[
            {
                "SAMPLE_ID": "SJINF001",
                "PATIENT_ID": "SJINF001",
                "MLL_STATUS": "INF_MLLr",
                "LEUKEMIA_TYPE": "Pre-B",
                "MUTATION_RATE": "3.97E-08",
                "GENE_PANEL": "WGS",
                "CANCER_TYPE": "Leukemia",
                "CANCER_TYPE_DETAILED": "B-Cell Acute Lymphoid Leukemia",
                "ONCOTREE_CODE": "BALL",
                "SOMATIC_STATUS": "Matched",
                "TMB_NONSYNONYMOUS": "0",
            },
            {
                "SAMPLE_ID": "SJINF001R",
                "PATIENT_ID": "SJINF001",
                "MLL_STATUS": "INF_MLLr",
                "LEUKEMIA_TYPE": "Pre-B",
                "MUTATION_RATE": "",
                "GENE_PANEL": "WGS",
                "CANCER_TYPE": "Leukemia",
                "CANCER_TYPE_DETAILED": "B-Cell Acute Lymphoid Leukemia",
                "ONCOTREE_CODE": "BALL",
                "SOMATIC_STATUS": "Matched",
                "TMB_NONSYNONYMOUS": "0",
            },
            {
                "SAMPLE_ID": "SJINF002",
                "PATIENT_ID": "SJINF002",
                "MLL_STATUS": "INF_MLLr",
                "LEUKEMIA_TYPE": "Pre-B",
                "MUTATION_RATE": "7.38E-08",
                "GENE_PANEL": "WGS",
                "CANCER_TYPE": "Leukemia",
                "CANCER_TYPE_DETAILED": "B-Cell Acute Lymphoid Leukemia",
                "ONCOTREE_CODE": "BALL",
                "SOMATIC_STATUS": "Matched",
                "TMB_NONSYNONYMOUS": "0",
            },
            {
                "SAMPLE_ID": "SJINF002R",
                "PATIENT_ID": "SJINF002",
                "MLL_STATUS": "INF_MLLr",
                "LEUKEMIA_TYPE": "Pre-B",
                "MUTATION_RATE": "",
                "GENE_PANEL": "WGS",
                "CANCER_TYPE": "Leukemia",
                "CANCER_TYPE_DETAILED": "B-Cell Acute Lymphoid Leukemia",
                "ONCOTREE_CODE": "BALL",
                "SOMATIC_STATUS": "Matched",
                "TMB_NONSYNONYMOUS": "0",
            },
            {
                "SAMPLE_ID": "SJINF003",
                "PATIENT_ID": "SJINF003",
                "MLL_STATUS": "INF_MLLr",
                "LEUKEMIA_TYPE": "Pre-B",
                "MUTATION_RATE": "3.96E-08",
                "GENE_PANEL": "WGS",
                "CANCER_TYPE": "Leukemia",
                "CANCER_TYPE_DETAILED": "B-Cell Acute Lymphoid Leukemia",
                "ONCOTREE_CODE": "BALL",
                "SOMATIC_STATUS": "Matched",
                "TMB_NONSYNONYMOUS": "0",
            },
        ],
        metadata=[
            {"type_of_cancer: bll": "cancer_study_identifier: all_stjude_2015"},
            {
                "type_of_cancer: bll": "name: Acute Lymphoblastic Leukemia (St Jude, Nat Genet 2015)"
            },
            {"type_of_cancer: bll": "short_name: ALL (St. Jude 2015)"},
            {
                "type_of_cancer: bll": "description: Comprehensive profiling of infant MLL-rearranged acute lymphoblastic leukemia (MLL-R ALL)"
            },
            {"type_of_cancer: bll": "citation: Andersson et al. Nat Genet 2015"},
            {"type_of_cancer: bll": "pmid: 25730765"},
            {"type_of_cancer: bll": "groups: PUBLIC"},
        ],
    )


@pytest.mark.ci_ok
def test_cbioportal_harvester(
    test_data_dir: Path, stjude_all_2015_fixture: CBioPortalHarvestedData, monkeypatch
):
    monkeypatch.setenv("WAGS_TAILS_DIR", test_data_dir.absolute().as_uri())
    harvested_data = CBioPortalHarvester().harvest(CBioPortalStudyName.ALL_STJUDE_2015)
    assert harvested_data == [stjude_all_2015_fixture]
