import { Typography, Box, Link, Stack, Divider } from '@mui/material'
import DocsLayout from '../../../components/docs/DocsLayout/DocsLayout'
import { useEffect } from 'react'

export default function SourcesPage() {
  useEffect(() => {
    document.title = 'VICC MetaKB Jr. | Sources'
  }, [])

  return (
    <DocsLayout>
      <Typography variant="h4" mb={2} fontWeight="bold">
        Current Sources
      </Typography>

      <Stack spacing={3} sx={{ mt: 3 }}>
        <Box>
          <Typography
            component={Link}
            href="https://civicdb.org/"
            target="_blank"
            rel="noopener"
            variant="h6"
            sx={{ textDecoration: 'none' }}
          >
            CIViC
          </Typography>

          <Typography variant="body2" color="text.secondary">
            Clinical Interpretation of Variants in Cancer knowledgebase.
          </Typography>

          <Typography variant="body2" sx={{ mt: 1 }}>
            Griffith M, Spies NC, Krysiak K, et al. CIViC is a community knowledgebase for expert
            crowdsourcing the clinical interpretation of variants in cancer.
            <i> Nature Genetics.</i> 2017;49(2):170–174.
          </Typography>

          <Typography variant="body2" sx={{ mt: 1 }}>
            Kilannin Krysiak, Arpad M Danos, Jason Saliba, et al. CIViCdb 2022: evolution of an
            open-access cancer variant interpretation knowledgebase, <i>Nucleic Acids Research</i>,
            Volume 51, Issue D1, 6 January 2023, Pages D1230–D1241,
            https://doi.org/10.1093/nar/gkac979{' '}
          </Typography>
        </Box>

        <Divider />

        <Box>
          <Typography
            component={Link}
            href="https://moalmanac.org/"
            target="_blank"
            rel="noopener"
            variant="h6"
            sx={{ textDecoration: 'none' }}
          >
            MOAlmanac
          </Typography>

          <Typography variant="body2" color="text.secondary">
            Molecular Oncology Almanac interpretation resource.
          </Typography>

          <Typography variant="body2" sx={{ mt: 1 }}>
            Reardon B, Moore ND, Moore NS, et al. Integrating molecular profiles into clinical
            frameworks through the Molecular Oncology Almanac.
            <i> Nature Cancer.</i> 2021.
          </Typography>
        </Box>

        <Divider />

        <Box>
          <Typography
            component={Link}
            href="https://www.fda.gov/about-fda/oncology-center-excellence/pediatric-oncology-drug-approvals"
            target="_blank"
            rel="noopener"
            variant="h6"
            sx={{ textDecoration: 'none' }}
          >
            FDA Pediatric Oncology Approvals
          </Typography>

          <Typography variant="body2" color="text.secondary">
            FDA drug approval and pediatric oncology indication data.
          </Typography>

          <Typography variant="body2" sx={{ mt: 1 }}>
            U.S. Food and Drug Administration. FDA-approved oncology therapies and pediatric
            indication resources, as curated{' '}
            <Link
              href="https://github.com/GenomicMedLab/fda_pediatric_oncology_drug_approvals"
              target="_blank"
              rel="noopener"
            >
              here
            </Link>
            .
          </Typography>
        </Box>

        <Divider />

        <Box>
          <Typography
            component={Link}
            href="https://ccdi.cancer.gov/MCI"
            target="_blank"
            rel="noopener"
            variant="h6"
            sx={{ textDecoration: 'none' }}
          >
            Molecular Characterization Initiative (MCI) Knowledge Pilot
          </Typography>

          <Typography variant="body2" color="text.secondary">
            A subsample of data generated by Nationwide Children's Hospital as part of a national
            molecular testing project led by the National Cancer Institute.
          </Typography>

          <Typography variant="body2" sx={{ mt: 1 }}>
            Diagnostic assessments rendered by Nationwide Children's Hospital clinicians and curated{' '}
            <Link
              href="https://github.com/GenomicMedLab/mci-knowledge-pilot/"
              target="_blank"
              rel="noopener"
            >
              here
            </Link>
            .
          </Typography>
        </Box>
      </Stack>
    </DocsLayout>
  )
}
