name: Branch workflow rules
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check_branch_names
        if: ${{ github.base_ref == 'main' && github.head_ref != 'staging' }}
        run: |
          echo "Head branch must be 'staging' when creating a PR where the base branch is 'main'"
          exit 1
