name: checks
on: [push, pull_request]
jobs:
  test_backend:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    defaults:
      run:
        working-directory: ./server
    services:
      neo4j:
        image: neo4j:5-community
        ports:
          - 7687:7687
          - 7474:7474
        env:
          NEO4J_AUTH: neo4j/test
          NEO4J_dbms_memory_heap_initial__size: 256m
          NEO4J_dbms_memory_heap_max__size: 512m
        options: >-
          --health-cmd "curl -fsS http://localhost:7474/ready || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra tests --extra dev --extra notebooks

      - name: Run tests
        working-directory: ./server
        run: uv run pytest -m "ci_ok or ci_only"
        env:
          METAKB_DB_URL: "bolt://neo4j:test@localhost:7687"

  lint_backend:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dev dependencies
        run: uv sync --extra dev

      - name: Check style
        run: uv run ruff check && uv run ruff format --check

  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - "end-of-file-fixer"
          - "trailing-whitespace"
          - "mixed-line-ending"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ matrix.cmd }} --all-files

  lint_frontend:
    name: Frontend lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        working-directory: ./client
        run: pnpm lint

      - name: Check formatting
        working-directory: ./client
        run: pnpm format

  docs:
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra docs
        working-directory: ./server

      - name: Attempt docs build
        working-directory: ./docs
        run: source ../server/.venv/bin/activate && make html
